# Generated by Django 4.1 on 2022-08-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_library', '0003_user_address_user_balance_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_photo',
            field=models.ImageField(blank=True, upload_to='media/book_covers'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/user_photos'),
        ),
    ]
