# Generated by Django 4.1 on 2022-08-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_library', '0005_remove_book_category_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='availabe_from',
            field=models.DateField(null=True),
        ),
    ]
