# Generated by Django 4.1 on 2022-08-21 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_library', '0007_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='virtual_library.book'),
            preserve_default=False,
        ),
    ]
