# Generated by Django 4.1 on 2022-08-21 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_library', '0008_rating_book'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('book', 'user')},
        ),
    ]
