# Generated by Django 4.1 on 2022-08-21 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_library', '0009_alter_rating_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='stars',
            new_name='rating',
        ),
    ]
